<?php

return [
    'clientes' => [
        'table' => 'clientes',
        'fields' => [
            'razao_social',
            'nome_fantasia',
            'cnpj',
            'inscricao_estadual',
            'email',
            'telefone',
            'celular',
            'endereco',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
            'cep',
            'responsavel_nome',
            'responsavel_email',
            'responsavel_telefone',
            'observacoes',
            'ativo',
        ],
        'order_by' => 'id DESC',
    ],
    'projetos' => [
        'table' => 'projetos',
        'fields' => [
            'nome',
            'codigo',
            'sigla',
            'descricao',
            'versao_atual',
            'ativo',
        ],
        'order_by' => 'id DESC',
    ],
    'planos' => [
        'table' => 'planos',
        'fields' => [
            'projeto_id',
            'nome',
            'descricao',
            'valor_mensal',
            'valor_anual',
            'max_usuarios',
            'max_dispositivos',
            'recursos',
            'ativo',
        ],
        'order_by' => 'id DESC',
    ],
    'perfis' => [
        'table' => 'perfis',
        'fields' => [
            'nome',
            'descricao',
            'permissoes',
        ],
        'order_by' => 'id DESC',
    ],
    'usuarios' => [
        'table' => 'usuarios',
        'fields' => [
            'nome',
            'email',
            'senha',
            'perfil_id',
            'ativo',
            'ultimo_acesso',
        ],
        'order_by' => 'id DESC',
    ],
    'licencas' => [
        'table' => 'licencas',
        'fields' => [
            'cliente_id',
            'projeto_id',
            'plano_id',
            'codigo_licenca',
            'chave_ativacao',
            'tipo_cobranca',
            'valor_cobrado',
            'data_inicio',
            'data_vencimento',
            'data_cancelamento',
            'status',
            'renovacao_automatica',
            'observacoes',
        ],
        'order_by' => 'id DESC',
    ],
    'cobrancas' => [
        'table' => 'cobrancas',
        'fields' => [
            'licenca_id',
            'cliente_id',
            'numero_fatura',
            'descricao',
            'valor',
            'desconto',
            'valor_final',
            'data_vencimento',
            'data_pagamento',
            'status',
            'forma_pagamento',
            'comprovante_url',
            'observacoes',
        ],
        'order_by' => 'id DESC',
    ],
    'pagamentos' => [
        'table' => 'pagamentos',
        'fields' => [
            'cobranca_id',
            'valor_pago',
            'data_pagamento',
            'forma_pagamento',
            'referencia_externa',
            'comprovante_url',
            'observacoes',
        ],
        'order_by' => 'id DESC',
    ],
    'notificacoes' => [
        'table' => 'notificacoes',
        'fields' => [
            'licenca_id',
            'cliente_id',
            'tipo',
            'titulo',
            'mensagem',
            'enviado_email',
            'data_envio_email',
            'lido',
        ],
        'order_by' => 'id DESC',
    ],
    'historico_licencas' => [
        'table' => 'historico_licencas',
        'fields' => [
            'licenca_id',
            'usuario_id',
            'acao',
            'status_anterior',
            'status_novo',
            'observacoes',
        ],
        'order_by' => 'id DESC',
    ],
    'validacoes_licenca' => [
        'table' => 'validacoes_licenca',
        'fields' => [
            'licenca_id',
            'cliente_id',
            'projeto_id',
            'cnpj',
            'sigla',
            'ip_origem',
            'status_retornado',
            'mensagem_retorno',
            'dados_request',
            'dados_response',
        ],
        'order_by' => 'id DESC',
    ],
];
